### ISSUE TITLE
Liquid XP Support for the XP crystal. 

### ISSUE THREAD

**Issue by PokerfaceCactus** [ChaoticTrials/UtilitiX#12]
### Describe your idea

Given the similarities between XP crystal and the XP obelisk from Ender IO. 
I thought it'd be really nice if the XP crystal could be expanded to allow for liquid XP from mods like mob grinding utils and sophisticated backpacks to be piped in/out of the crystal like the XP obelist from Ender IO used to allow.

**Comment by MelanX** [comment]
That’s definitely planned. I just want to wait for the internal rewrite of Forges fluid system. I had to rewrite my stuff if I would add it now. I only have limited time for modding because of other stuff. If I can avoid writing the stuff two times, I prefer to wait to only do it once :D

**Comment by PokerfaceCactus** [comment]
Yeah that's sensible. hope the forge rewrite is gonna be any good for your sake then though so you don't still have to rewrite stuff :P

**Comment by PokerfaceCactus** [comment]
Any updates on this? it happened to come up in conversation with a friend today and I thought I'd see if there was any news on this.

**Comment by MelanX** [comment]
Since I have no time for coding at the moment because of exams, I'm not able to work on this. The new system by Forge is still in development, so I guess... I could start this once I have more time. Maybe it's done before porting to 1.19 :)
