### ISSUE TITLE
Glue Ball does not stick things together with Quark installed 

### ISSUE THREAD

**Issue by Mattabase** [ChaoticTrials/UtilitiX#13]
### Minecraft version

1.18.1

### LibX version

LibX-1.18.1-3.1.8

### UtilitiX version

UtilitiX-1.18.1-0.3.8

### Forge version

39.0.56

### The latest.log file

https://gist.github.com/Mattabase/c121bbac7362f40eed3c9bc416673ab7

### Issue description

The "Glue Ball" does not function correctly with Quark installed, it can be placed but the blocks do not stick together

### Steps to reproduce

Use the glue ball as you would without Quark installed, the blocks do not stick

### Other information

This is my own testing modpack, I have not tested with just Quark and this mod, however removing just Quark does fix the issue and Quark does change piston logic

**Comment by MelanX** [comment]
I tested a bit and tried to fix this. Now, I added a warning when the config in quark is enabled to replace the piston logic. If it's disabled, the glue works fine.
If I have enough time, I try fixing that completely, but for now you need to just disable this config option.
