### ISSUE TITLE
How do "filter rail"(s) work?

### ISSUE THREAD

**Issue by Garonne** [ChaoticTrials/UtilitiX#20]
I can't find any guides on how "filter rail"s are supposed to work... hitting with the wrench doesn't do anything... I can open the gui of the track but... no matter what I do, minecarts go straight across the filter rail.

**Comment by noeppi-noeppi** [comment]
You shift right click the rail with a minecart tinkerer. Then you'll get an inventory where you place a filter item. Left clicking any minecart with a minecart tinkerer will open a GUI where you can add a filter item to that cart. Any minecart which has the same filter item set as the filter rail will then move around the corner. Any other minecart will go straight.

**Comment by Garonne** [comment]
Ahhh... Thanks... Didn't see there's a way to open a GUI on minecarts as well... does it work with all kinds of carts (i.e. non-utilitix, non-minecraft carts... like create or any other ones)?

Ok... Reading the "U"-Info carefully would have helped... Sorry for being stupid.

**Comment by noeppi-noeppi** [comment]
It should work on all types of minecarts, even carts from other mods.
