### ISSUE TITLE
Comparator Redirector not stacking

### ISSUE THREAD

**Issue by Azus5** [ChaoticTrials/UtilitiX#25]
### Minecraft version

1.18.2

### LibX version

1.8.2-3.2.18

### UtilitiX version

1.8.2-0.4.6

### Forge version

40.1.60

### The latest.log file

https://gist.github.com/Azus5/7b3a049145de3129bd501290933333a5

### Issue description

This could very well be considered a "feature" request, I'm creating as a bug, because this is something I consider not to be the expected behavior. The comparator redirector (up & down) do not stack / carry on the signal, so for instance if you place a chest with items in it and place two of the mentioned blocks, the first one will carry the signal (allowing you to use a comparator) but the second one don't.

Please let me know if I'm missing something here. Love your mod(s)!

### Steps to reproduce

- Place a chest and fill it with items
- place two "Comparator Redirector" (either 'Up" or "Down")
- second redirector does not carry the signal.

### Other information

Playing All The Mods 7 (0.4.23)

**Comment by Azus5** [comment]
Looking at the code, I see it's actually intentional. I'm going to keep this as a ""bug"", just because for what I mentioned in the issue description
> I consider not to be the expected behavior

I'd like to know why ignore other redirectors

**Comment by MelanX** [comment]
Yes, this is intentional. I don't want them to be used for chaining. Fully intentional, will not change that behaviour. If you want something like that, you may want to use include the linked repeater in your setup, or use another mod with wireless redstone things for that.
