### ISSUE TITLE
Roadmap in README is out of date (w.r.t. Quiver item)

### ISSUE THREAD

**Issue by James103** [ChaoticTrials/UtilitiX#32]
### Minecraft version

1.19.2

### LibX version

4.2.8

### UtilitiX version

0.7.3

### Forge version

43.1.55

### The latest.log file

Not needed (can provide if required)

### Issue description

The Quiver item is present in the mod, however, its line in the README roadmap is left unchecked.

### Steps to reproduce

1. Check the README, and notice that the line that says "Quiver" is left unchecked.
2. Create a new instance with Minecraft 1.19.2 and Forge 43.1.55.
3. Install LibX 4.2.8 and UtilitiX 0.7.3.
4. Create a new world with cheats enabled.
5. Notice that the Quiver item is present in the UtilitiX mod.

**Comment by MelanX** [comment]
It’s correct as it is, the Quiver isn’t done yet. It has nearly no functionality, is only available by cheating, and has no recipe.
