### ISSUE TITLE
Double Door Opening Conflict with Quark

### ISSUE THREAD

**Issue by kcddagger** [ChaoticTrials/UtilitiX#38]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.8

### UtilitiX version

1.19.2-0.7.7

### Forge version

43.2.4

### The latest.log file

https://gist.github.com/kcddagger/095c732abfac357f5081e27ba38b776e#file-latest-log

### Issue description

I noticed that double doors would not open.  They would instead make a door rattle sound and act as if they are locked.  Single doors work as intended.  If an illager opened one of the doors and I was fast enough to click the other door, the door I clicked would stay open when the illager used door closed.

A person in a discord server pointed out that Quark does things with doors so I used that as a starting point.

I removed quark, and the double doors started working again.

I then did a binary search for the mod(s) that would be in conflict with quark and found that UtilitiX was the only other mod to conflict in such a way that the double doors stopped working.

I have disabled UtilitiX until such time as this can be resolved.  However I would like to say that I really like some of the other things this mod brings into the game and would like to play with both enabled.

### Other information

I am using quark-3.4-394

**Comment by MelanX** [comment]
For now, you could disable this feature in the config, should be called "doubleDoor" in `utilitix.json5`.

For me, I like to link this issue:
- https://github.com/MelanX/UtilitiX/issues/36

I wanted to link the issue where someone reported exactly the same with Quark and double door. Sadly, I think this was only reported on Discord. I hate it 🗡️ 

Thanks for reporting!

**Comment by kcddagger** [comment]
Thank you.  being able to disable that resolved the conflict.

I'll pass this on to the friends that also play on my server so we can all be on the same page
