### ISSUE TITLE
[1.19.2] Logs said to report this issue

### ISSUE THREAD

**Issue by itsdinkd** [ChaoticTrials/UtilitiX#40]
### Minecraft version

1.19.2

### LibX version

4.2.8

### UtilitiX version

0.7.8

### Forge version

40.2.2

### The latest.log file

https://gist.github.com/itsdinkd/ebfb00e86f48efe35173d96eca1881e7

### Issue description

Tried joining world, got invalid player data all of a sudden. checked logs and am getting spammed a message to report the stacktrace here 
![image](https://user-images.githubusercontent.com/35115304/236296270-a99dc9ac-c110-46b6-afb9-349bf2d4784a.png)

### Steps to reproduce

Do not have steps.

**Comment by MelanX** [comment]
Thank you. The logging message also asks for the complete modlist but I think it’s caused by REI, thanks!

**Comment by itsdinkd** [comment]
Sorry - I forget that forge doesnt have modlist in latest log
