### ISSUE TITLE
How am I supposed to get an Ancient Compass?

### ISSUE THREAD

**Issue by jpisthebest** [ChaoticTrials/UtilitiX#41]
Me and my friends are in a server and are trying to find an Anceint city, we have this mod installed and saw it, but it seemed there was no recipe, and we can't find any info on it, can someone please help?

**Comment by MelanX** [comment]
It’s loot in mob spawner rooms, chance 1/32.
And yes, wiki is still planned, sorry :D

**Comment by jpisthebest** [comment]
So like mob dungeons and stuff? Sorry if I seem silly- Just really confused.

**Comment by MelanX** [comment]
Yes. Where the mob spawners are :)
