### ISSUE TITLE
Make High Speed Rail Handle Inclines

### ISSUE THREAD

**Issue by bcrotty** [ChaoticTrials/UtilitiX#42]
### Describe your idea

Currently the High Speed Rail won't connect up a block like a normal rail. It would be great if it did.

![image](https://github.com/MelanX/UtilitiX/assets/6155964/471a1eed-854b-431c-99eb-1d690d28417f)

**Comment by MelanX** [comment]
As mentioned in the JEI description, this is intended. Thus, this will not change, even if I understand your point. It's for balancing :)

**Comment by bcrotty** [comment]
Understood. I don't see a description in JEI though.
![image](https://github.com/MelanX/UtilitiX/assets/6155964/b78c2420-40ef-4c9e-af77-aa706013bf0c)

**Comment by MelanX** [comment]
![image](https://github.com/MelanX/UtilitiX/assets/26039509/42d6d0e7-28e8-4244-939d-01ec782ffd41)
