### ISSUE TITLE
Crashing with JEI in ATM9

### ISSUE THREAD

**Issue by PandaBeariano** [ChaoticTrials/UtilitiX#43]
### Minecraft version

1.20.1

### LibX version

5.0.2

### UtilitiX version

0.8.0

### Forge version

47.0.34

### The latest.log file

https://mclo.gs/i5q4hPh

### Issue description

When i have it enabled i get an JEI error:

![image](https://github.com/MelanX/UtilitiX/assets/136627449/9904e37e-a525-46a9-ad94-1dbac5373fb9)

### Other information
Crash log
https://mclo.gs/uTjbzvF

**Comment by MelanX** [comment]
Did it happen only once, or does it happen all the time?

**Comment by Mitchell5200** [comment]
some users are getting it all the time, others have not, you can refer to #atm9-help in the ATM discord,
