### ISSUE TITLE
Can't use the gilding crystal

### ISSUE THREAD

**Issue by TiphaineLAURENT** [ChaoticTrials/UtilitiX#47]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.5

### UtilitiX version

1.20.1-0.8.2

### Forge version

47.1.3

### The latest.log file

-

### Issue description

Minecraft 1.20 comes with a new Smithing table which requires templates.
I believe this part did not get migrate yet but I wish to inform you that there is currently no way to use the gilding crystal as it is missing the template component from the recipe.

**Comment by MelanX** [comment]
I saw something in JEI with the gilding stuff but I worked on something different at that moment. I thought I fixed gilding, too. Sorry for that, will fix it asap.

**Comment by MelanX** [comment]
Ehm... Could you demonstrate the opposite to me? 
https://github.com/MelanX/UtilitiX/assets/26039509/d18df279-a8d7-4560-bc89-739cd760a91a

**Comment by TiphaineLAURENT** [comment]
Oh you are right, it works for diamond chestplates
![image](https://github.com/MelanX/UtilitiX/assets/25824254/fade854d-7107-41b8-98ee-5084390f1d80)

It is not working with the Awakened Suprenium Chestplate from Mystical Agriculture but I should have reported that to them sorry.

Thank you

**Comment by MelanX** [comment]
Maybe this armor already has something like that. If it already has this ability, you can’t gild it.
