### ISSUE TITLE
Issue on Loading my World

### ISSUE THREAD

**Issue by Estacionancio** [ChaoticTrials/UtilitiX#48]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.5

### UtilitiX version

1.20.1-0.8.2

### Forge version

47.1.3

### The latest.log file

https://mclo.gs/P404LxU

### Issue description

Im having problems joining my single player survival world because of the "Mob Bell" Item, Whenever i try to join the world, it instantly saves and closes the modpack

### Other information

I've tried to downgrade the modpack's updates (ATM 9) |0.0.48 version to 0.0.46 (the last version that i could join my world)|

**Comment by MelanX** [comment]
Why do you know that the Mob Bell is the problem? I can't find any information about that in your crash report. By the way, you just sent the crash report, not the latest.log. latest.log does have more information to work with. Maybe I'd see the mob bell mention in this one?

**Comment by Gbergz** [comment]
Got the same crash, pretty sure it's it, something related to a bell.

https://gist.github.com/Gbergz/c63223a576544597952b8ea31ea049d2

**Versions:**
UtilitiX: 0.8.2
LibX: 5.0.5
MC: 1.20.1
Forge: 47.1.3
