### ISSUE TITLE
server crashes when loading a specific mine colony area

### ISSUE THREAD

**Issue by domshi** [ChaoticTrials/UtilitiX#50]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.5

### UtilitiX version

1.20.1-0.8.8

### Forge version

47.1.3

### The latest.log file

https://gist.github.com/domshi/b6718dfa59408f6caf3e56ca6c589ba2

### Issue description

when i load into the server to my mine colony area it produces these errors and crashes the server 15 seconds later

### Steps to reproduce

unknown as other mine colonies are unaffected, however if anyone loads my mine colony area, the server crashes

### Other information

console error log 
![image](https://github.com/MelanX/UtilitiX/assets/90562421/9e8fe89e-7713-4412-a0ed-a522018e16a0)

**Comment by MelanX** [comment]
Please read in the template: 
> Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc.
For more information, see https://git.io/mclogs

**Comment by domshi** [comment]
> Please read in the template:
> 
> > Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc.
> > For more information, see https://git.io/mclogs

ok, sorry didn't know if links to other things are standard.
Fixed, is there anything us server moderators can do to stop this crash?

**Comment by MelanX** [comment]
Is it always a crash with UtilitiX? And if you create a backup and try without UtilitiX, does it still crash? For me, it looks like the server is just too busy. And maybe AE2 does a bit too much (in this stacktrace). I think it’s not UtilitiX fault, but you need to test this.
