### ISSUE TITLE
Xp Crystal cannot receive (or at very slow speed) xp fluid from Absorption Hopper from Mob Grinding Utils

### ISSUE THREAD

**Issue by Taskeren** [ChaoticTrials/UtilitiX#52]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.8

### UtilitiX version

1.20.1-0.8.9

### Forge version

47.2.16

### The latest.log file

/

### Issue description

Absorption Hopper exports fluid directly to Experience Crystal is at a very slow speed, or even not working at all.
But when I use a Mechanical Pipe (from Mek) to connect both of them, it works fine.

### Steps to reproduce

/

### Other information

Tested on ATM-9 0.2.28.

**Comment by MelanX** [comment]
Whats slow for you? It takes a few seconds to empty the whole absorption hopper into the crystal. I can say that the Experience Crystal is not the limiting part here. Here you see that the absorption hopper has a limit: 
https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.20.1-forge/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/tile/TileEntityAbsorptionHopper.java#L254
Here you see that Experience Crystal accepts everything all at once: https://github.com/MelanX/UtilitiX/blob/1.20.x/src/main/java/de/melanx/utilitix/content/experiencecrystal/TileExperienceCrystal.java#L178

I think that Mekanism Pipes don't accept the fluid, but instead they drain it from the hopper. By doing this, they can set the limit for extraction.

**Comment by Taskeren** [comment]
So it can be the automatical extraction amount is too small for a high efficient mob farm.

**Comment by MelanX** [comment]
That is true but cannot be solved by me. The only thing would be that I implemented draining into the crystal but that’s a thing I don’t want.
Another solution for a mob farm would be that you put the crystal in the farm. Xp orbs move towards the crystal and the crystal will absorb them. Similar to the absorption hopper, but not instantly and without teleportation.
