### ISSUE TITLE
Please add the minecraft:boats tag to the shulker boats

### ISSUE THREAD

**Issue by RedAngel121** [ChaoticTrials/UtilitiX#67]
### Describe your idea

add `minecraft:boats` tag to the following items
utilitix:acacia_shulker_boat
utilitix:birch_shulker_boat
utilitix:cherry_shulker_boat
utilitix:dark_oak_shulker_boat
utilitix:jungle_shulker_boat
utilitix:mangrove_shulker_boat
utilitix:oak_shulker_boat
utilitix:spruce_shulker_boat
utilitix:bamboo_shulker_raft

**Comment by MelanX** [comment]
It's just the item tag, right?

**Comment by RedAngel121** [comment]
Yes I believe it is just the item tag, I'm currently using kubejs to assign that tag to those items. I figured it would be easier for you to put it in the mod so other people can use it too

**Comment by MelanX** [comment]
Thank you, will add it today for 1.19+ versions
