### ISSUE TITLE
Crash When Combining two uncolored/empty Backpacks

### ISSUE THREAD

**Issue by xilef310** [ChaoticTrials/UtilitiX#68]
### Minecraft version

1.20.1

### LibX version

5.0.14

### UtilitiX version

0.8.22

### Forge version

47.3.7

### The latest.log file

https://pastebin.com/4gfdUWLg

### Issue description

When combining 2 freshly crafted, empty, uncolored backpacks. The game crashed.
with "The game crashed whilst container click
Error: java.lang.ArithmeticException: / by zero"

I did previously combined some and it worked. Just now I colored one backpack and combining with that one now worked.
Im guessing the missing color is the issue.

### Steps to reproduce

0. Play ATM9
1. Get two basic unmodified backpacks.
2. Combine them in your inventory with right click
3. Should crash

### Other information

I am playing ATM9 0.3.2 btw.

**Comment by MelanX** [comment]
Does ATM9 add the backpack to a blacklist for sorting mods? If not, please never sort inventory in backpack inv :D See #66
