### ISSUE TITLE
Experience Crystal loses all stored exp on server restart

### ISSUE THREAD

**Issue by DeclanHawkes1** [ChaoticTrials/UtilitiX#8]
**Versions**

Minecraft: 1.18.1
Forge: 39.0.9/forge
LibX: 
UtilitX: 
Modpack: ATM7 v 0.2.13 and earlier at this point 

**Describe the bug**
Any experience stored in crystal when server is restarted is lost.

**How to reproduce**

1. Put exp in crystal
2. Have server restart
3. don't profit

**Expected behavior**

**Screenshots**

**Comment by MelanX** [comment]
Happens on singleplayer, too.

**Comment by MelanX** [comment]
It happens with *all* Block Entities, not only the XP Crystal.

**Comment by DeclanHawkes1** [comment]
It was also happening with Iron Furnaces mod losing the inventory, they fixed that in today's update.
the Beyond Earth or Modular Routers machines do not lose inventory however. (all in the ATM7 pack)
I know nothing about programming so hopefully my info will help.

**Comment by MelanX** [comment]
Sorry, with "*all* Block Entities", I mean only the block entities of UtilitiX :D Anyways, thank you for the information with the other mods, maybe it helps :)
